import React from 'react';

const FeedbackModal = ({ isCorrect, onClose }) => {
    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
            <div className="bg-white p-6 rounded-lg text-center max-w-sm w-full">
                <h3 className="text-xl font-bold mb-2">
                    {isCorrect ? 'Correct!' : 'Incorrect'}
                </h3>
                <p className="mb-4">
                    {isCorrect
                        ? 'You correctly identified the real person.'
                        : 'This image was generated by AI. Try again!'}
                </p>
                <button
                    onClick={onClose}
                    className="bg-gray-700 text-white px-4 py-2 rounded hover:bg-gray-800"
                >
                    Next
                </button>
            </div>
        </div>
    );
};

export default FeedbackModal;